### ISSUE TITLE
Not working...doesn't load library?

### ISSUE THREAD

**Issue by ElixirMike** [bytepark/country_icons#1]
I installed this, reference it as top, and tried to use. 

I keep getting error like this:
Unable to load asset: packages/country_icons/icons/flags/us.png

Is there something else that needs to be configured?

**Comment by ToniTornado** [comment]
The example seem outdated. The image files are in subfolders for png or svg. Try using `packages/country_icons/icons/flags/png/us.png` as source path.

**Comment by ash2osh** [comment]
+1

**Comment by tjerkw** [comment]
Doesnt seem to work: 
════════ Exception caught by image resource service ════════════════════════════
Unable to load asset: packages/country_icons/icons/flags/png/en.png

**Comment by fbatschi** [comment]
A new example has been added to the package
