### ISSUE TITLE
Missing Wales & Scotland flag

### ISSUE THREAD

**Issue by nerder** [bytepark/country_icons#13]
As in title, we miss the Wales and Scotland flag

**Comment by tierecke** [comment]
I guess you could add a lot of flags of states in the US and other territories that don't have an Internet domain code.  
What would be the codes for those flags then?

**Comment by fbatschi** [comment]
After newest version of flags from upstream have been included, Scotland and Wales are available (`gb-sct` and `gb-wls`)
