### ISSUE TITLE
[feature] Allow alpha3 country code

### ISSUE THREAD

**Issue by fvisticot** [bytepark/country_icons#7]
It seems this package is based on alpha2.
Sometime alpha3 is required: https://fr.wikipedia.org/wiki/ISO_3166-1

**Comment by fbatschi** [comment]
This package is based on the flags of http://hjnilsson.github.io/country-flags which are named as alpha2. 

so they can't be referenced directly with alpha3. 

only way would maybe to have an translation function within this package with translates from alpha3 to alpha2.
Feel free to submit a PR for this.

**Comment by fvisticot** [comment]
tx for your quick reply.
I will try find time to make the feature but if you wants some information:

alfa3 codes: https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-country-api-queries

In attach a json file with alfa2 / alfa3 from previous website

[countries.json.zip](https://github.com/bytepark/country_icons/files/6561064/countries.json.zip)
